import './main.css'
import './blocks/guest-dropdown/guest-dropdown'
import './blocks/calendar/datepicker.css'
import '../node_modules/air-datepicker/dist/js/datepicker.js'
import './blocks/calendar/calendar.js'