import './main.css'
import './plugins/jquery-ui.css'
import './plugins/jquery-ui'
import './blocks/buttons/range-slider/range-slider'
import './blocks/dropdowns/room-info-dropdown/room-info-dropdown'
import './blocks/guest-dropdown/guest-dropdown'
import './blocks/dropdowns/conveniences-checkbox-dropdown/checkbox-list-dropdown'